### ISSUE TITLE
not adding all actors and not showing all actors in player client

### ISSUE THREAD

**Issue by Conandy1970** [Sk1mble/Popcorn#6]
I just installed this (FoundryVTT ver. 0.7.9).  I am finding that Popcorn Initiative doesn't always show all the actors who are in the combat. However, if I use Poporn tracker to clear the encounter, and start over, it grabs all the actors who are in combat.  It seems like Popcorn holds some data in a cache or something that doesn't clear out and reset. 

Also, it I open Popcorn in a player window, it doesn't show all the actors in that combat.  As GM I started a combat, opened Popcorn, verified that all actors were present in Popcorn.  Then opened popcorn in a player window, and it only shows a few of the combatants.

**Comment by Sk1mble** [comment]
Fixed in 1.2.1
