### ISSUE TITLE
Mismatch between v1.2.1 manifest and release

### ISSUE THREAD

**Issue by rdeforest** [Sk1mble/Popcorn#7]
The manifest has "download" set to "https://github.com/Sk1mble/Popcorn/archive/V1.2.1.zip", which has an upper-case 'V'. The release was created with a lower-case 'v'.

Also you may wish to change your default branch to master or make a release branch or ... something.

**Comment by Sk1mble** [comment]
I've fixed this in 1.2.2. Thanks!
